name: TerraformApply

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "The stage to deploy to"
        required: false
        default: "dev"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v4
      - name: terraform-apply
        uses: proxyserver2023/alexandria/github-workflows/terraform-apply@dev
        with:
          stage: ${{ inputs.stage || 'dev' }}
          terraform_path: terraform/
